// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOQyRO_Kuqwh_hPsA4m_VbuaV4KyyT8Nc',
    appId: '1:361136169919:web:0b7d91d0aab834e8b6370a',
    messagingSenderId: '361136169919',
    projectId: 'gad-lift',
    authDomain: 'gad-lift.firebaseapp.com',
    storageBucket: 'gad-lift.appspot.com',
    measurementId: 'G-L323P92J1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAppWapQf4LxAGFUS2QHgvC7QeNP2wvqDc',
    appId: '1:361136169919:android:5e3136f1a2ec1240b6370a',
    messagingSenderId: '361136169919',
    projectId: 'gad-lift',
    storageBucket: 'gad-lift.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATa1_jJxFP8UttJ73yRCf6A6gwRA-eAgo',
    appId: '1:361136169919:ios:279348119236ad81b6370a',
    messagingSenderId: '361136169919',
    projectId: 'gad-lift',
    storageBucket: 'gad-lift.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATa1_jJxFP8UttJ73yRCf6A6gwRA-eAgo',
    appId: '1:361136169919:ios:b67693c02102bbdeb6370a',
    messagingSenderId: '361136169919',
    projectId: 'gad-lift',
    storageBucket: 'gad-lift.appspot.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
