name: mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.0.4
  google_fonts: ^6.1.0
  http: ^1.1.2
  sign_in_button: ^3.2.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  dio: ^5.4.0
  flutter_svg: ^2.0.9
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/